# Generated by Django 6.0.1 on 2026-01-11 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='اسم الدفعة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='اسم المتقدم')),
                ('national_id', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='السجل المدني')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='رقم الجوال')),
                ('current_job', models.CharField(blank=True, default='', max_length=50, verbose_name='العمل الحالي')),
                ('years_deputy', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='سنوات عمل وكيل')),
                ('years_director', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='سنوات عمل مدير')),
                ('applicant_school', models.CharField(blank=True, default='', max_length=255, verbose_name='مدرسة المتقدم')),
                ('applicant_sector', models.CharField(blank=True, default='', max_length=255, verbose_name='قطاع المتقدم')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفرصة/المدرسة')),
                ('sector', models.CharField(blank=True, default='', max_length=255, verbose_name='القطاع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_role', models.CharField(choices=[('مدير', 'مدير'), ('وكيل', 'وكيل'), ('أخرى', 'أخرى')], default='مدير', max_length=50, verbose_name='الوظيفة المتقدم عليها')),
                ('file_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='درجة الملف')),
                ('interview_score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='درجة المقابلة')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6, verbose_name='المجموع الكلي')),
                ('is_eligible', models.BooleanField(default=False, editable=False, verbose_name='مستوفي الشرط')),
                ('ineligible_reason', models.CharField(blank=True, default='', editable=False, max_length=255, verbose_name='سبب الاستبعاد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tarsheeh.batch')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tarsheeh.candidate')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='tarsheeh.opportunity')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'opportunity'], name='tarsheeh_ap_batch_i_1c4636_idx'), models.Index(fields=['is_eligible', '-total_score'], name='tarsheeh_ap_is_elig_70a7d3_idx')],
            },
        ),
    ]
